Repository googleapis/nodejs-storage, pull requests merged in 2018-06, with the labels that each got.

#223 Fix permission of bash script for Kokoro
  .kokoro/sample_tests.sh
Labels: cla: yes

#202 Update to the latest version of nodejs-common and gcs-resumable-upload
  .gitignore
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
  src/acl.js
  src/bucket.js
  src/file.js
  system-test/storage.js
  test/bucket.js
  test/file.js
Labels: cla: yes

#234 fix: signedURL cname (#210)
  src/file.js
  test/file.js
Labels: cla: yes

#242 Major semver: drop node 4 support
  .circleci/config.yml
  package-lock.json
  package.json
  samples/package-lock.json
Labels: Breaking Change, cla: yes, semver: major

#246 refactor(es6): Refactor constructor pattern as ES6 class
  src/acl.js
  src/bucket.js
  src/channel.js
  src/file.js
  src/iam.js
  src/index.js
  src/notification.js
  test/index.js
Labels: cla: yes

#252 fix: move this.[ROLE]s initialization from Acl to AclAccessorRoleMethods
  src/acl.js
Labels: cla: yes, type: bug

#254 fix: update linking for samples
  .circleci/config.yml
Labels: cla: yes

#256 chore: weed the lock file
  samples/package-lock.json
Labels: cla: yes

#255 Typescript conversion (initial)
  .clang-format
  package-lock.json
  package.json
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/iam.ts
  src/index.ts
  src/notification.ts
  tsconfig.json
  tslint.json
Labels: cla: yes

#258 fix: drop repo-tools as an exec wrapper
  .circleci/config.yml
  package.json
  samples/package.json
Labels: cla: yes

#260 Typescript: internalize class and object members into class
  package-lock.json
  package.json
  src/acl.ts
  src/bucket.ts
  src/file.ts
  src/iam.ts
  src/index.ts
Labels: cla: yes

#261 Typescript: add 'any' type to suppress compiler error
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/index.ts
  src/notification.ts
Labels: cla: yes

#265 chore: update gcs-resumable-upload to 0.11.1
  package-lock.json
  package.json
Labels: cla: yes

#267 Typescript: use ts-style exports instead of module.exports
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/iam.ts
  src/index.ts
  src/notification.ts
Labels: cla: yes

#268 Typescript: misc. fixes to make tsc happy
  src/acl.ts
  src/bucket.ts
  src/file.ts
  src/iam.ts
  src/index.ts
  src/notification.ts
Labels: cla: yes
