Repository googleapis/nodejs-storage, pull requests merged in 2018-07, with the labels that each got.

#272 Typescript: convert tests to typescript (1)
  package-lock.json
  package.json
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: cla: yes

#280 fix: test meant to assert err msg exists, but instead asserted msg greater than -1
  test/file.js
Labels: cla: yes, type: bug

#271 Typescript: setup package.json and .circleci/config.yaml
  .circleci/config.yml
  package.json
Labels: cla: yes, in progress

#281 Typescript: tests (2)
  test/bucket.ts
  test/file.ts
  test/notification.ts
  tsconfig.json
Labels: TypeScript, cla: yes

#282 fix: cleanup CircleCI config
  .circleci/config.yml
Labels: cla: yes

#225 gzip and Cache-Control headers in upload sample
  samples/files.js
Labels: cla: yes

#286 Typescript: require Storage from build location
  test/acl.ts
  test/index.ts
Labels: cla: yes

#287 refactor(ts): import individual exports from @google-cloud/common
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/iam.ts
  src/index.ts
  src/notification.ts
Labels: cla: yes

#290 TypeScript: make test/notification.ts pass
  test/channel.ts
  test/iam.ts
  test/notification.ts
Labels: cla: yes

#288 refactor(ts): make test/acl.ts pass
  test/acl.ts
Labels: cla: yes

#292 TypeScript: make test/index.ts pass
  src/index.ts
  test/index.ts
Labels: cla: yes

#289 build: test-no-cover should compile ts before running test
  .circleci/config.yml
  package-lock.json
  package.json
  test/mocha.opts
Labels: cla: yes

#293 cleanup(codecov): ignore build/test for code coverage
  package.json
Labels: cla: yes

#291 TypeScript: make Bucket test pass
  test/bucket.ts
Labels: cla: yes

#294 TypeScript: make test/file.ts pass
  src/file.ts
  test/file.ts
Labels: cla: yes

#295 refactor(ts): run gts fix
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: cla: yes

#297 refactor(ts): function to arrow =>
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: cla: yes

#298 Revert "refactor(ts): function to arrow =>"
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: cla: yes

#299 Typescript: tests function() to arrow =>
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: TypeScript, cla: yes

#300 refactor(ts): tslint:disable-next-line:variable-name
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: TypeScript, cla: yes

#308 test: use assert.deepStrictEqual in tests
  .circleci/config.yml
  package-lock.json
  samples/package-lock.json
  samples/package.json
  system-test/storage.js
  test/acl.js
  test/bucket.js
  test/channel.js
  test/file.js
  test/iam.js
  test/index.js
  test/notification.js
Labels: cla: yes

#306 test: use strictEqual in tests
  .circleci/config.yml
  package-lock.json
  samples/package-lock.json
  samples/package.json
  system-test/storage.js
  test/acl.js
  test/bucket.js
  test/channel.js
  test/file.js
  test/iam.js
  test/index.js
  test/notification.js
Labels: cla: yes

#311 chore: move mocha options to mocha.opts
  package.json
  test/mocha.opts
Labels: cla: yes

#307 Typescript: workaround explicit 'any' cast in tests
  test/bucket.ts
  test/file.ts
  test/notification.ts
Labels: cla: yes
