Repository googleapis/nodejs-storage, pull requests merged in 2018-02, with the labels that each got.

#133 add 'auto' options for contentType and gzip
  package.json
  src/file.js
  test/file.js
Labels: cla: no

#127 Mention the required scope for `getSignedUrl` and `getSignedPolicy`.
  src/file.js
Labels: cla: yes

#135 1.6.0
  package.json
  samples/package.json
Labels: cla: yes

#136 chore: run CI as non-root user
  .circleci/config.yml
Labels: cla: yes

#137 docs: add performance note to File#save.
  src/file.js
Labels: cla: yes, docs

#139 chore: removing node7 job from CircleCI
  .circleci/config.yml
Labels: cla: yes
