Repository googleapis/nodejs-storage, pull requests merged in 2019-10, with the labels that each got.

#870 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: cla: yes

#850 feat: add flag to allow disabling auto decompression by client
  src/file.ts
  test/file.ts
Labels: cla: yes

#873 feat: allow setting standard Bucket storage class
  src/storage.ts
  test/index.ts
Labels: cla: yes

#872 fix: pass predefined acl as destinationPredefinedAcl to qs
  src/file.ts
  system-test/storage.ts
  test/file.ts
Labels: cla: yes

#874 fix: file#move do not delete origin file if same as destination
  src/file.ts
  test/file.ts
Labels: automerge, cla: yes

#881 chore: update CONTRIBUTING.md and make releaseType node
  .github/release-please.yml
  CONTRIBUTING.md
Labels: cla: yes

#878 refactor: clarify the error message for file#move
  src/file.ts
  test/file.ts
Labels: cla: yes

#876 feat(bucket): add enableLogging method
  src/bucket.ts
  system-test/storage.ts
  test/bucket.ts
Labels: cla: yes

#820 fix!: allow leading slashes in file name
  src/file.ts
  test/file.ts
Labels: Breaking Change, cla: yes

#893 Revert "fix: use storage.googleapis.com for api endpoint"
  src/file.ts
  src/storage.ts
  test/file.ts
  test/index.ts
Labels: cla: yes

#896 fix(docs): missing quote in signed url jsdoc
  src/file.ts
Labels: cla: yes

#899 fix: use storage.googleapis.com for api endpoint
  src/file.ts
  src/storage.ts
  test/file.ts
  test/index.ts
Labels: cla: yes

#871 docs: readme.md to include creation of service account client
  samples/quickstart.js
Labels: cla: yes

#892 docs: explain how to use delimiter and prefix
  src/bucket.ts
Labels: cla: yes

#910 docs: updated readme with new quickstart
  README.md
  synth.metadata
Labels: cla: yes

#911 test: include src/ in coverage
  .nycrc
  synth.metadata
Labels: cla: yes

#905 fix(signed-url): replace encodeURIComponent with custom encoding function
  conformance-test/test-data/v4SignedUrl.json
  src/file.ts
  src/util.ts
  system-test/storage.ts
  test/file.ts
Labels: cla: yes

#903 feat: [Storage] Support UniformBucketLevelAccess
  samples/buckets.js
  samples/system-test/buckets.test.js
  system-test/storage.ts
Labels: cla: yes
