Repository googleapis/nodejs-storage, pull requests merged in 2019-03, with the labels that each got.

#623 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#624 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#629 tests: fix assertion syntax
  test/bucket.ts
  test/channel.ts
Labels: cla: yes

#628 Release @google-cloud/storage v2.4.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#630 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#634 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#639 docs: add a .repo-metadata.json
  .repo-metadata.json
Labels: cla: yes

#632 docs: clarify in docs, the meaning of ASIA and coldline
  samples/buckets.js
Labels: :rotating_light:, automerge, cla: yes, type: docs

#643 fix: do not download cached files
  src/file.ts
  test/file.ts
Labels: cla: yes

#633 docs: document destination option
  samples/files.js
Labels: :rotating_light:, automerge, cla: yes

#640 docs: add additional api_id field
  .repo-metadata.json
Labels: cla: yes

#644 docs: add requires_billing, retire .cloud-repo-tools.json
  .cloud-repo-tools.json
  .repo-metadata.json
Labels: cla: yes

#648 docs: update README format
  README.md
  synth.metadata
Labels: cla: yes

#646 test(v2-sign): add multi-valued headers system-test
  src/file.ts
  system-test/storage.ts
Labels: cla: yes

#647 docs(samples): refactor the quickstart to match the new rubric
  samples/quickstart.js
  samples/system-test/quickstart.test.js
Labels: cla: yes

#645 docs: new synthtool generated README
  .gitignore
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#650 docs: slight difference in how nightly synthtool run generated README
  README.md
  synth.metadata
Labels: cla: yes
