Repository googleapis/nodejs-storage, pull requests merged in 2019-08, with the labels that each got.

#789 build: add Node 12 remove Node 11
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/test.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/test.cfg
Labels: cla: yes

#791 docs(samples): Add get bucket metadata sample
  samples/bucketMetadata.js
  samples/system-test/buckets.test.js
Labels: cla: yes

#792 fix: allow calls with no request, add JSON proto
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#793 docs(samples): HMAC SA Admin Samples
  .kokoro/setup-vars.sh
  samples/hmacKeyActivate.js
  samples/hmacKeyCreate.js
  samples/hmacKeyDeactivate.js
  samples/hmacKeyDelete.js
  samples/hmacKeyGet.js
  samples/hmacKeysList.js
  samples/system-test/hmacKey.test.js
  test/index.ts
Labels: cla: yes, kokoro:force-run

#788 test: add benchmarking wrapper
  bin/README.md
  bin/benchwrapper.js
  bin/storage.proto
  package.json
  src/storage.ts
Labels: cla: yes

#802 tests: fix system tests
  system-test/storage.ts
Labels: cla: yes

#642 feat(file): allow setting configPath of resumable upload
  src/file.ts
  test/file.ts
Labels: cla: yes

#801 HMAC key: projectId option
  src/hmacKey.ts
  src/storage.ts
  test/hmacKey.ts
  test/index.ts
Labels: cla: yes

#795 fix(deps): upgrade @google-cloud/common version to show original error message
  package.json
  system-test/storage.ts
Labels: cla: yes

#800 fix(deps): use the latest extend
  package.json
Labels: cla: yes

#803 chore: release 3.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#750 feat: HMAC System tests
  .kokoro/setup-vars.sh
  system-test/storage.ts
Labels: cla: yes

#809 fix(deps): update @google-cloud/common with fixes for http
  package.json
Labels: cla: yes

#810 feat(test): hmac key - service account pool and fix tests
  .kokoro/pre-system-test.sh
  .kokoro/setup-vars.sh
  README.md
  samples/README.md
  samples/hmacKeyActivate.js
  samples/hmacKeyCreate.js
  samples/hmacKeyDeactivate.js
  samples/hmacKeyDelete.js
  samples/hmacKeyGet.js
  samples/hmacKeysList.js
  samples/system-test/hmacKey.test.js
  synth.metadata
  system-test/storage.ts
Labels: cla: yes

#812 test: add test for x-goog-api-client header
  bin/benchwrapper.js
  package.json
  test/headers.ts
Labels: cla: yes

#804 chore: add TLS to benchwrapper
  bin/benchwrapper.js
  bin/certificate/server.key
  bin/certificate/server.pem
Labels: cla: yes

#816 test: remove tls for benchwrapper
  bin/README.md
  bin/benchwrapper.js
  bin/certificate/server.key
  bin/certificate/server.pem
Labels: cla: yes

#819 fix(ts): fix nock @~11.0.0
  package.json
Labels: cla: yes

#751 feat: hmac service account
  .kokoro/pre-system-test.sh
  .kokoro/setup-vars.sh
  README.md
  samples/README.md
  samples/hmacKeyActivate.js
  samples/hmacKeyCreate.js
  samples/hmacKeyDeactivate.js
  samples/hmacKeyDelete.js
  samples/hmacKeyGet.js
  samples/hmacKeysList.js
  samples/system-test/hmacKey.test.js
  src/hmacKey.ts
  src/index.ts
  src/storage.ts
  synth.metadata
  system-test/storage.ts
  test/hmacKey.ts
  test/index.ts
Labels: cla: yes

#823 chore: release 3.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#824 nit: update license headers
  samples/acl.js
  samples/bucketLock.js
  samples/buckets.js
  samples/encryption.js
  samples/files.js
  samples/hmacKeyActivate.js
  samples/iam.js
  samples/notifications.js
  samples/quickstart.js
  samples/requesterPays.js
  samples/scripts/cleanup
  samples/system-test/acl.test.js
  samples/system-test/bucketLock.test.js
  samples/system-test/buckets.test.js
  samples/system-test/encryption.test.js
  samples/system-test/files.test.js
  samples/system-test/iam.test.js
  samples/system-test/notifications.test.js
  samples/system-test/quickstart.test.js
  samples/system-test/requesterPays.test.js
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/iam.ts
  src/notification.ts
  src/util.ts
  synth.py
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/iam.ts
  test/notification.ts
Labels: cla: yes

#837 revert: remove unsupported keepAcl param from file#copy
  src/file.ts
Labels: cla: yes
