Repository googleapis/nodejs-storage, pull requests merged in 2019-04, with the labels that each got.

#638 test: v4 signed URL: conformance test
  conformance-test/fixtures/signing-service-account.json
  conformance-test/test-data/v4SignedUrl.json
  conformance-test/v4SignedUrl.ts
  package.json
  src/file.ts
  tsconfig.json
Labels: :rotating_light:, cla: yes

#657 chore(deps): upgrade to newest version of @google-cloud/common
  package.json
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/notification.ts
  src/storage.ts
Labels: cla: yes

#660 refactor: replace once with onetime
  package.json
  src/file.ts
Labels: cla: yes

#649 docs: regenerate the samples/README.md
  README.md
  package.json
  samples/README.md
  synth.metadata
Labels: :rotating_light:, cla: yes

#654 docs(samples): Samples for v4 Signed URL
  samples/files.js
  samples/package.json
  samples/resources/.gitignore
  samples/system-test/files.test.js
Labels: cla: yes

#637 feat: introduce v4 signed url
  conformance-test/fixtures/signing-service-account.json
  conformance-test/test-data/v4SignedUrl.json
  conformance-test/v4SignedUrl.ts
  package.json
  samples/files.js
  samples/package.json
  samples/resources/.gitignore
  samples/system-test/files.test.js
  src/file.ts
  src/util.ts
  system-test/storage.ts
  test/file.ts
  tsconfig.json
Labels: :rotating_light:, cla: yes

#665 Release @google-cloud/storage v2.5.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#664 refactor: use execSync for tests
  samples/package.json
  samples/system-test/acl.test.js
  samples/system-test/bucketLock.test.js
  samples/system-test/buckets.test.js
  samples/system-test/encryption.test.js
  samples/system-test/files.test.js
  samples/system-test/iam.test.js
  samples/system-test/notifications.test.js
  samples/system-test/quickstart.test.js
  samples/system-test/requesterPays.test.js
Labels: automerge, cla: yes

#666 fix(ts): improve return types for response metadata
  package.json
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/iam.ts
  src/notification.ts
  src/storage.ts
  test/acl.ts
  test/bucket.ts
  test/index.ts
Labels: cla: yes

#680 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
