Repository googleapis/nodejs-storage, pull requests merged in 2019-05, with the labels that each got.

#684 fix: validate action of getSignedUrl() function
  src/file.ts
  test/file.ts
Labels: cla: yes

#689 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#688 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#691 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#698 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#699 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#696 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#700 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#703 fix(types): fix signatures of listing methods
  src/bucket.ts
  src/index.ts
  src/storage.ts
Labels: cla: yes, kokoro:force-ci

#702 refactor: remove usage of async module
  package.json
  src/bucket.ts
  system-test/storage.ts
Labels: cla: yes

#715 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#721 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#723 test: async is still used in tests
  package.json
Labels: cla: yes

#722 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#726 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#727 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#708 feat: add file.isPublic() function
  package.json
  src/file.ts
  system-test/storage.ts
  test/file.ts
Labels: :rotating_light:, cla: yes

#728 feat: support apiEndpoint override
  package.json
  src/storage.ts
  test/index.ts
Labels: cla: yes
