Repository googleapis/nodejs-storage, pull requests merged in 2019-06, with the labels that each got.

#734 build: remove unused clang format
  .clang-format
  samples/bucketLock.js
  src/file.ts
  test/file.ts
Labels: automerge, cla: yes

#738 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#719 chore: release 3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#743 fix: async should be dependency
  package.json
Labels: cla: yes

#745 chore: release 3.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#749 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#747 refactor: remove async usage from bucket
  package.json
  src/bucket.ts
  test/bucket.ts
Labels: cla: yes

#753 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#752 docs: detailed clarification of 'getSignedUrl' method docs
  src/file.ts
Labels: cla: yes

#757 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes

#759 fix(docs): fix sample code in docs
  src/file.ts
Labels: cla: yes
