Repository googleapis/nodejs-storage, pull requests merged in 2020-08, with the labels that each got.

#1261 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1238 docs: update outdated references to signBlob API documentation
  src/bucket.ts
  src/file.ts
Labels: cla: yes

#1265 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1207 docs: rename setTemporarydHold and address README
  README.md
  samples/README.md
  samples/setTemporaryHold.js
  samples/system-test/bucketLock.test.js
Labels: cla: yes

#1267 docs: update list of available samples
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1268 build: perform publish using Node 12, chore: update cloud rad kokoro build job, updates to README
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge: exact, cla: yes, context: partial

#1273 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#1272 docs: add startOffset, endOffset and includeTrailingDelimiter in get files options
  src/bucket.ts
  system-test/storage.ts
Labels: cla: yes

#1216 feat: support noncurrent time object lifecycle condition
  src/bucket.ts
  system-test/storage.ts
  test/bucket.ts
Labels: cla: yes

#1278 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full
