Repository googleapis/nodejs-storage, pull requests merged in 2020-07, with the labels that each got.

#1234 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#1241 test: should throw original error message on non JSON response on large metadata
  system-test/storage.ts
Labels: cla: yes

#1242 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, gitattribute.*, in

#1240 feat: remove through2 dependency
  package.json
  src/file.ts
  system-test/storage.ts
  test/bucket.ts
  test/file.ts
Labels: cla: yes

#1246 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1225 fix: support request interceptors for file uploads
  package.json
  src/file.ts
  test/file.ts
Labels: cla: yes, status: blocked

#1253 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: cla: yes

#1250 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none

#1251 build: type in .gittatribute, missing closing paren in publish script, delete template for Node 8 tests, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1259 build: rename __toc to toc, move gitattributes files to node templates #811
  .gitattributes
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#1260 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
