Repository googleapis/nodejs-storage, pull requests merged in 2020-09, with the labels that each got.

#1285 feat: add custom time field in metadata sample
  samples/getMetadata.js
Labels: api: storage, cla: yes

#1292 docs(samples): file archived generations sample
  samples/copyOldVersionOfFile.js
  samples/deleteOldVersionOfFile.js
  samples/listFilesWithOldVersions.js
  samples/system-test/files.test.js
Labels: api: storage, cla: yes

#1295 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1296 build: update to latest test config
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: cla: yes, context: partial

#1280 docs(samples): bucket cors configuration sample
  samples/configureBucketCors.js
  samples/removeBucketCors.js
  samples/system-test/buckets.test.js
Labels: api: storage, cla: yes, samples

#1298 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1299 fix(types): add `CreateBucketRequest.storageClass`
  src/storage.ts
Labels: cla: yes

#1303 docs(terminology): update language to follow recommendations
  system-test/storage.ts
Labels: automerge, cla: yes

#1300 test: fix flaky test should get metadata for an HMAC key
  system-test/storage.ts
Labels: api: storage, cla: yes

#1304 refactor(deps): replace concat-stream with get-stream
  package.json
  src/file.ts
Labels: api: storage, cla: yes
