Repository googleapis/nodejs-storage, pull requests merged in 2020-11, with the labels that each got.

#1332 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#1331 docs: fix typo in readme
  bin/README.md
Labels: api: storage, cla: yes

#1328 feat: accessibleAt v4 signed urls
  src/file.ts
  src/signer.ts
  system-test/storage.ts
  test/file.ts
  test/signer.ts
Labels: api: storage, cla: yes

#1317 fix(docs): explain manual pagination and add usage sample
  samples/listFilesPaginate.js
  samples/system-test/files.test.js
  src/bucket.ts
  src/storage.ts
Labels: api: storage, cla: yes, samples

#1342 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: api: storage, cla: yes, context: none

#1345 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#1323 fix: error if both `storageClass` and specific storage class name are provided
  src/storage.ts
  test/index.ts
Labels: api: storage, cla: yes
