Repository googleapis/nodejs-storage, pull requests merged in 2020-05, with the labels that each got.

#1135 fix(bucket): Only disable resumable uploads for bucket.upload (fixes #1133)
  src/bucket.ts
  test/bucket.ts
Labels: cla: yes

#1169 fix(v4-policy): encode special characters
  conformance-test/v4SignedUrl.ts
  src/file.ts
  src/util.ts
  test/file.ts
Labels: cla: yes

#1168 fix(v4-policy): add missing bucket field
  src/file.ts
  test/file.ts
Labels: cla: yes

#1176 chores(build): add conformance-test to workflow
  .github/workflows/conformance-test.yaml
Labels: cla: yes

#1167 fix: sync to googleapis/conformance-tests@fa559a1
  conformance-test/test-data/v4SignedUrl.json
  src/file.ts
  test/file.ts
Labels: cla: yes

#1179 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#1182 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#1186 fix(deps): update gcs-resumable-upload, remove gitnpm usage
  package.json
  src/bucket.ts
  src/file.ts
Labels: cla: yes

#1185 build: point to team in correct org
  .github/CODEOWNERS
Labels: cla: yes

#1074 feat: enable bytes read tracking
  src/bucket.ts
  src/file.ts
  system-test/storage.ts
  test/file.ts
Labels: cla: yes

#1166 chore!: drop `keepAcl` parameter in file copy
  src/file.ts
  test/file.ts
Labels: cla: yes

#1190 feat!: automatically detect contentType if not provided
  src/bucket.ts
  src/file.ts
  test/bucket.ts
  test/file.ts
Labels: cla: yes

#1161 fix: StorageOptions.apiEndpoint overrides simple and resumable uploads
  src/file.ts
  src/storage.ts
  test/file.ts
  test/index.ts
Labels: cla: yes, kokoro:run

#1196 nit: resolve lint warnings
  src/bucket.ts
  src/file.ts
  system-test/storage.ts
Labels: cla: yes

#1198 fix(types): assert in typescript 3.7
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/index.ts
Labels: cla: yes

#1195 samples: enable bucket lifecycle management
  samples/enableBucketLifecycleManagement.js
  samples/system-test/bucketLifecycle.test.js
Labels: cla: yes

#1203 samples: disable lifecycle management
  samples/disableBucketLifecycleManagement.js
  samples/system-test/bucketLifecycle.test.js
Labels: cla: yes
