Repository googleapis/nodejs-storage, pull requests merged in 2020-01, with the labels that each got.

#908 feat: add support for Archive storage class
  src/bucket.ts
  src/file.ts
  src/storage.ts
  test/index.ts
Labels: cla: yes, do not merge, status: blocked

#970 chore: exclude .d.ts in .nycrc
  .nycrc
  synth.metadata
Labels: cla: yes

#965 build: use c8 for coverage
  package.json
Labels: cla: yes

#968 refactor: use explicit mocha imports
  conformance-test/v4SignedUrl.ts
  samples/system-test/.eslintrc.yml
  samples/system-test/acl.test.js
  samples/system-test/bucketLock.test.js
  samples/system-test/buckets.test.js
  samples/system-test/encryption.test.js
  samples/system-test/files.test.js
  samples/system-test/hmacKey.test.js
  samples/system-test/iam.test.js
  samples/system-test/notifications.test.js
  samples/system-test/quickstart.test.js
  samples/system-test/requesterPays.test.js
  system-test/storage.ts
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/headers.ts
  test/hmacKey.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: cla: yes

#974 fix: do not modify constructor options argument
  src/storage.ts
  test/index.ts
Labels: cla: yes

#993 fix: refactor getRetentionPolicy sample into its own file
  samples/bucketLock.js
  samples/getRetentionPolicy.js
  samples/system-test/bucketLock.test.js
Labels: cla: yes

#1030 fix: refactor rotateEncryptionKey sample into its own file
  samples/encryption.js
  samples/rotateEncryptionKey.js
  samples/system-test/encryption.test.js
Labels: cla: yes

#1028 fix: refactor uploadEncryptedFile sample into its own file
  samples/encryption.js
  samples/system-test/encryption.test.js
  samples/uploadEncryptedFile.js
Labels: cla: yes, kokoro:run

#1031 docs: adds new samples to README
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#977 chore: refactoring deleteBucket sample into a new file
  samples/buckets.js
  samples/deleteBucket.js
  samples/downloaded.txt
  samples/system-test/buckets.test.js
Labels: cla: yes

#979 chore: refactoring enableUniformBucketLevelAccess sample into its own file
  samples/buckets.js
  samples/enableUniformBucketLevelAccess.js
  samples/system-test/buckets.test.js
Labels: cla: yes

#980 fix: refactoring disableUniformBucketLevelAccess into its own file
  samples/buckets.js
  samples/disableUniformBucketLevelAccess.js
  samples/enableDefaultKMSKey.js
  samples/system-test/buckets.test.js
  src/file.ts
Labels: cla: yes

#981 fix: refactor getUniformBucketLevelAccess into its own file
  samples/buckets.js
  samples/getUniformBucketLevelAccess.js
  samples/system-test/buckets.test.js
Labels: cla: yes

#1035 docs: update READMEs for split samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#973 docs(samples): storage IAM condition
  samples/iam.js
  samples/system-test/iam.test.js
Labels: cla: yes

#1020 feat: add support for CORS as a first class citizen
  src/bucket.ts
  src/storage.ts
  system-test/storage.ts
  test/bucket.ts
Labels: cla: yes

#1008 fix: refactor getMetadata sample into its own file
  samples/files.js
  samples/getMetadata.js
  samples/system-test/files.test.js
Labels: cla: yes

#1039 build: update windows configuration to match new vm
  .kokoro/test.bat
Labels: cla: yes

#1042 fix(samples): fix overwritten IAM conditions sample
  samples/addBucketIamMember.js
  samples/removeBucketIamMember.js
  samples/system-test/iam.test.js
  samples/viewBucketIamMembers.js
Labels: cla: yes

#948 test(system): debug flaky test
  system-test/storage.ts
Labels: cla: yes, do not merge

#1049 chore: clear synth.metadata
  synth.metadata
Labels: cla: yes

#1050 chore: generate synth.metadata
  synth.metadata
Labels: cla: yes

#1058 docs(readme): log errors in sample
  README.md
  synth.metadata
Labels: cla: yes
