Repository googleapis/nodejs-storage, pull requests merged in 2020-06, with the labels that each got.

#1211 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: partial

#1208 feat: allow setting timeouts on uploads
  src/bucket.ts
  src/file.ts
  test/file.ts
Labels: cla: yes

#1217 docs: add note about using service account
  samples/generateV4ReadSignedUrl.js
Labels: automerge, cla: yes

#1210 fix(deps): update dependency p-limit to v3
  package.json
  src/bucket.ts
  system-test/storage.ts
  test/bucket.ts
Labels: cla: yes

#1220 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: cla: yes, context: full

#1228 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full
