Repository googleapis/nodejs-storage, pull requests merged in 2020-02, with the labels that each got.

#1060 chore: skip img.shields.io in docs test
  linkinator.config.json
Labels: cla: yes

#1063 fix: skip validation for server decompressed objects
  src/file.ts
  system-test/storage.ts
  test/file.ts
Labels: cla: yes

#1066 test(signed-url): update conformance test json to conformance-test@9f134282
  conformance-test/test-data/v4SignedUrl.json
  conformance-test/v4SignedUrl.ts
Labels: cla: yes

#1068 fix(signed-url): trailing `/` after path before query params
  conformance-test/v4SignedUrl.ts
  src/signer.ts
Labels: cla: yes

#1071 build: add GitHub actions config for unit tests
  .github/workflows/ci.yaml
  package.json
Labels: cla: yes

#1069 fix(signed-url): fix query parameter signing
  src/bucket.ts
  src/file.ts
  src/signer.ts
  test/bucket.ts
  test/signer.ts
Labels: cla: yes

#1067 feat(signed-url): support virtual hosted style url
  conformance-test/v4SignedUrl.ts
  src/bucket.ts
  src/file.ts
  src/signer.ts
  system-test/storage.ts
  test/file.ts
  test/signer.ts
Labels: cla: yes, kokoro:run

#1070 feat(signed-url): support SHA256 for signed payloads
  conformance-test/v4SignedUrl.ts
  src/file.ts
  src/signer.ts
  src/util.ts
  test/file.ts
  test/signer.ts
Labels: cla: yes

#1082 test: fix storage perf benchwrapper
  bin/benchwrapper.js
Labels: cla: yes

#1084 build: add publish.yml enabling GitHub app for publishes
  .github/publish.yml
Labels: automerge, cla: yes

#1086 chore: update jsdoc.js
  .jsdoc.js
Labels: automerge, cla: yes

#1088 chore: correct .jsdoc.js protos and double quotes
  .jsdoc.js
Labels: automerge, cla: yes, kokoro:force-run
