Repository googleapis/nodejs-storage, pull requests merged in 2020-12, with the labels that each got.

#1339 fix: add publicUrl to exclude promisifyAll
  src/file.ts
  test/file.ts
Labels: api: storage, cla: yes

#1346 fix: only throw if `storageClass` and specific storage class name provide different values
  src/storage.ts
  test/index.ts
Labels: api: storage, cla: yes

#1301 docs: storage class docs in create bucket
  src/storage.ts
Labels: api: storage, cla: yes, type: docs

#1347 feat: allow ignoring 404 errors during delete() operations
  package.json
  src/bucket.ts
  src/file.ts
Labels: api: storage, cla: yes

#1354 docs: add properties and missing methods
  src/bucket.ts
  src/file.ts
  src/hmacKey.ts
  src/notification.ts
  src/storage.ts
Labels: api: storage, cla: yes

#1355 feat: support metadata updates from makePrivate() methods
  src/bucket.ts
  src/file.ts
  test/bucket.ts
  test/file.ts
Labels: api: storage, cla: yes

#1359 fix: jsdoc for bucket
  src/bucket.ts
Labels: api: storage, cla: yes

#1358 fix: capitalize action in Bucket#addLifecycleRule
  src/bucket.ts
  system-test/storage.ts
  test/bucket.ts
Labels: api: storage, cla: yes

#1279 docs(samples): enable/disable bucket's versioning sample
  samples/disableBucketVersioning.js
  samples/enableBucketVersioning.js
  samples/system-test/buckets.test.js
Labels: api: storage, automerge, cla: yes, samples

#1293 docs(samples): storage class and location sample
  samples/changeDefaultStorageClass.js
  samples/createBucketWithStorageClassAndLocation.js
  samples/fileChangeStorageClass.js
  samples/system-test/buckets.test.js
  samples/system-test/files.test.js
Labels: api: storage, cla: yes, samples

#1361 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: api: storage, cla: yes, context: none

#1364 docs: updated README
  README.md
  samples/README.md
  synth.metadata
Labels: api: storage, cla: yes, context: none, kokoro:force-run

#1270 docs(samples): add/remove bucket labels sample
  samples/addBucketLabel.js
  samples/removeBucketLabel.js
  samples/system-test/buckets.test.js
Labels: api: storage, cla: yes, samples

#1367 docs: updated README
  README.md
  samples/README.md
  synth.metadata
Labels: api: storage, cla: yes, context: none

#1369 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: storage, cla: yes, context: full
