Repository googleapis/nodejs-storage, pull requests merged in 2020-10, with the labels that each got.

#1306 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#1307 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: storage, automerge: exact, cla: yes, context: full

#1318 fix: self-upload files for Unicode system tests
  system-test/storage.ts
Labels: cla: yes

#1311 feat: add File#rename
  samples/renameFile.js
  samples/system-test/files.test.js
  src/file.ts
  system-test/storage.ts
  test/file.ts
Labels: api: storage, cla: yes

#1320 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1324 feat: public url of a file
  src/file.ts
  test/file.ts
Labels: cla: yes

#1313 feat(userAgent): allow for optional user agent to be provided
  src/storage.ts
Labels: api: storage, automerge, cla: yes

#1327 fix: moved publicUrl comment
  src/file.ts
Labels: cla: yes

#1329 docs: updated code of conduct/build files
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#1316 fix: set customEndpoint for custom environments
  src/storage.ts
  test/index.ts
Labels: api: storage, cla: yes
