Repository googleapis/nodejs-storage, pull requests merged in 2021-09, with the labels that each got.

#1577 build: updated sync-repo-settings
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage

#1578 build(config): yaml had invalid line
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: storage

#1575 samples: remove redundant contentEncoding
  samples/fileSetMetadata.js
Labels: cla: yes, api: storage, samples

#1574 tests: fixed typo
  test/bucket.ts
Labels: cla: yes, api: storage

#1582 chore: Revert "chore(nodejs): update client ref docs link in metadata (#1535)"
  .repo-metadata.json
  README.md
Labels: cla: yes, api: storage

#1583 fix: remove duplicated definition of BucketOptions and make sure prop…
  src/bucket.ts
  src/storage.ts
Labels: cla: yes, api: storage

#1585 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
  .repo-metadata.json
Labels: cla: yes, api: storage

#1586 chore: Label deprecated options with TS style syntax
  src/bucket.ts
  src/file.ts
  src/storage.ts
Labels: cla: yes, api: storage

#1587 fix(build): set default branch to main
  .github/generated-files-bot.yml
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .github/workflows/conformance-test.yaml
  README.md
  samples/README.md
Labels: cla: yes, api: storage

#1567 WIP: retry strategy runner code
  conformance-test/libraryMethods.ts
  conformance-test/retryStrategy.ts
  conformance-test/test-data/retryInvocationMap.json
  conformance-test/test-data/retryStrategyTestData.json
Labels: cla: yes, api: storage

#1591 fix: fixed runtime errors. all the tests still fail, but they run now
  conformance-test/retryStrategy.ts
Labels: cla: yes, api: storage

#1594 fix: retry strategy bug fixes
  conformance-test/libraryMethods.ts
  conformance-test/retryStrategy.ts
Labels: cla: yes, api: storage

#1601 feat: check that instructions were utilized in testbench
  conformance-test/retryStrategy.ts
Labels: cla: yes, api: storage

#1602 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, automerge, api: storage

#1603 fix: remove all files from bucket before delete
  conformance-test/libraryMethods.ts
Labels: cla: yes, api: storage

#1604 fix: set autoretry back to instance value at end of file functions
  src/file.ts
  test/file.ts
Labels: cla: yes, api: storage

#1605 feat: move test creation and header set to beforeEach
  conformance-test/retryStrategy.ts
Labels: cla: yes, api: storage

#1608 fix: create client for each test instead of globally
  conformance-test/retryStrategy.ts
Labels: cla: yes, api: storage

#1610 fix: remove bucketGet
  conformance-test/test-data/retryInvocationMap.json
Labels: cla: yes, api: storage

#1612 fix: return promise from stream functions and resolve on end
  conformance-test/libraryMethods.ts
Labels: cla: yes, api: storage

#1613 fix: move createReadStream to correct mapping location
  conformance-test/test-data/retryInvocationMap.json
Labels: cla: yes, api: storage

#1615 fix: remap bucket set storage class and bucket set metadata
  conformance-test/test-data/retryInvocationMap.json
Labels: cla: yes, api: storage

#1620 tests: skip unspecified pap tests
  samples/system-test/buckets.test.js
  system-test/storage.ts
Labels: cla: yes, api: storage

#1617 fix: respect precondition settings from constructors
  src/bucket.ts
  src/file.ts
  test/bucket.ts
  test/file.ts
Labels: cla: yes, api: storage

#1626 docs: correctly tag timeout option in CreateWriteStreamOptions
  src/file.ts
Labels: cla: yes, api: storage

#1627 fix: fixed bucketUploadMultipart
  conformance-test/libraryMethods.ts
Labels: cla: yes, api: storage

#1628 docs: updated notification region tags
  src/bucket.ts
  src/notification.ts
Labels: cla: yes, api: storage

#1629 docs: updated gcs-resumable-upload link
  src/file.ts
Labels: cla: yes, api: storage

#1593 samples: added retry samples
  .github/workflows/ci.yaml
  README.md
  linkinator.config.json
  samples/README.md
  samples/configureRetries.js
  samples/system-test/files.test.js
Labels: cla: yes, api: storage, samples, owlbot:ignore
