Repository googleapis/nodejs-storage, pull requests merged in 2021-01, with the labels that each got.

#1372 chore(deps): update date-and-time dependency to 0.14.2
  package.json
Labels: api: storage, cla: yes

#1370 fix: deprecated directory. prefix should be used instead
  src/bucket.ts
  system-test/storage.ts
  test/bucket.ts
Labels: api: storage, cla: yes

#1294 docs(sample): add missing samples
  samples/addBucketWebsiteConfiguration.js
  samples/changeFileCSEKToCMEK.js
  samples/composeFile.js
  samples/downloadPublicFile.js
  samples/getServiceAccount.js
  samples/makeBucketPublic.js
  samples/removeDefaultKMSKey.js
  samples/system-test/buckets.test.js
  samples/system-test/encryption.test.js
  samples/system-test/files.test.js
  samples/system-test/requesterPays.test.js
Labels: api: storage, automerge, cla: yes, samples

#1380 docs: Updated README
  README.md
  samples/README.md
  synth.metadata
Labels: api: storage, cla: yes, context: none

#1385 fix: retry multipart uploads on File.save()
  package.json
  src/file.ts
  test/file.ts
Labels: api: storage, cla: yes

#1390 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full
