Repository googleapis/nodejs-storage, pull requests merged in 2022-01, with the labels that each got.

#1737 chore: add api_shortname and library_type to repo metadata
  .repo-metadata.json
  README.md
Labels: api: storage

#1736 chore(deps): gcs-resumable-upload migration
  package.json
  src/file.ts
  src/gcs-resumable-upload/index.ts
  system-test/kitchen.ts
  test/file.ts
  test/fixtures/keys.json
  test/gcs-resumable-upload.ts
Labels: api: storage

#1648 feat: add support for rpo (turbo replication) metadata field when cre…
  src/storage.ts
  test/index.ts
Labels: cla: yes, api: storage

#1745 fix: remove compodoc dev dependency
  package.json
Labels: api: storage

#1618 sample: add turbo replication samples
  README.md
  samples/README.md
  samples/createBucketWithTurboReplication.js
  samples/getMetadata.js
  samples/getRPO.js
  samples/setRPOAsyncTurbo.js
  samples/setRPODefault.js
  samples/system-test/buckets.test.js
  system-test/storage.ts
Labels: cla: yes, api: storage, samples

#1754 feat: Expose `chunkSize` param for `CreateResumableUploadOptions`
  src/file.ts
  test/file.ts
Labels: api: storage

#1757 chore: pin testbench version
  conformance-test/test-bench-util.ts
Labels: api: storage

#1760 test: reduce retry delay multiplier to reduce test time
  conformance-test/retryStrategy.ts
Labels: api: storage

#1761 test: reduce number of operations and make names more unique
  conformance-test/libraryMethods.ts
  conformance-test/retryStrategy.ts
  conformance-test/test-bench-util.ts
Labels: api: storage

#1762 chore: fix typo in function name
  conformance-test/retryStrategy.ts
Labels: api: storage

#1764 fix(gcs-resumable-upload): Stop Duplicate Response Handlers on Retries
  src/gcs-resumable-upload/index.ts
  test/gcs-resumable-upload.ts
Labels: api: storage

#1769 test: wait for testbench docker container to be ready
  conformance-test/retryStrategy.ts
Labels: api: storage

#1767 samples: renamed upload without authentication sample
  README.md
  samples/README.md
  samples/system-test/files.test.js
  samples/uploadWithoutAuthentication.js
Labels: api: storage, samples
