Repository googleapis/nodejs-storage, pull requests merged in 2022-05, with the labels that each got.

#1904 test: fix types in signer test for typescript update
  test/signer.ts
Labels: api: storage, size: s

#1899 feat!: drop node 10 support
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package.json
  samples/package.json
Labels: api: storage, size: m

#1903 test: disable resumable upload in acl test before
  system-test/storage.ts
Labels: api: storage, size: xs

#1905 build: Streamline `mocha` config
  package.json
Labels: api: storage, size: s

#1917 refactor!: Misc cleanup
  package.json
  src/channel.ts
  src/file.ts
  system-test/storage.ts
Labels: api: storage, size: s

#1914 refactor(gcs-resumable-upload): Remove `pumpify` and `stream-events`
  src/gcs-resumable-upload.ts
  test/gcs-resumable-upload.ts
Labels: api: storage, size: m

#1855 test: add perf metrics utilities for write 1 / read 3
  internal-tooling/README.md
  internal-tooling/performPerformanceTest.ts
  internal-tooling/performanceTest.ts
  package.json
  tsconfig.json
Labels: api: storage, size: l

#1924 refactor(deps): remove snakeize dependency and create equivalent func…
  package.json
  src/bucket.ts
  src/util.ts
  test/bucket.ts
Labels: api: storage, size: s

#1923 refactor(common): remove unused operations class, tests, and poll int…
  src/nodejs-common/index.ts
  src/nodejs-common/operation.ts
  src/nodejs-common/service-object.ts
  test/nodejs-common/index.ts
  test/nodejs-common/operation.ts
Labels: api: storage, size: l

#1925 refactor(deps): Remove get-stream in favor of async iterators
  conformance-test/testBenchUtil.ts
  package.json
  src/file.ts
  test/file.ts
Labels: api: storage, size: s

#1928 refactor(deps): Remove date-and-time in favor of utility function
  package.json
  src/file.ts
  src/signer.ts
  src/util.ts
  test/file.ts
  test/signer.ts
Labels: api: storage, size: m

#1932 fix: do not use import on package.json
  src/nodejs-common/util.ts
Labels: api: storage, size: xs

#1936 fix: use path.join and __dirname for require package.json
  src/gcs-resumable-upload.ts
  src/nodejs-common/util.ts
  src/storage.ts
Labels: api: storage, size: s

#1940 deps: update teeny-request to 8.0
  package.json
Labels: api: storage, size: xs

#1941 fix: move retrieval of package.json to utility function
  src/gcs-resumable-upload.ts
  src/nodejs-common/util.ts
  src/storage.ts
  src/util.ts
Labels: api: storage, size: m

#1947 fix: revert native typescript mocha tests
  conformance-test/libraryMethods.ts
  conformance-test/v4SignedUrl.ts
  package.json
  src/gcs-resumable-upload.ts
  src/nodejs-common/util.ts
  src/storage.ts
  src/util.ts
  system-test/storage.ts
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/gcs-resumable-upload.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: api: storage, size: m

#1949 Fix: Support Empty Object Uploads for Resumable Upload
  src/gcs-resumable-upload.ts
  test/gcs-resumable-upload.ts
Labels: api: storage, size: m

#1950 chore!: rename `gcs-resumable-upload` -> `resumable-upload`
  src/file.ts
  src/resumable-upload.ts
  system-test/kitchen.ts
  test/file.ts
  test/resumable-upload.ts
Labels: automerge, api: storage, size: s

#1952 fix(chore): MODULE_NOT_FOUND uuid
  package.json
Labels: api: storage, size: xs

#1951 feat!: Use `HashStreamValidator` for Data Validation
  package.json
  src/bucket.ts
  src/crc32c.ts
  src/file.ts
  src/hash-stream-validator.ts
  src/index.ts
  src/storage.ts
  test/bucket.ts
  test/file.ts
  test/index.ts
Labels: api: storage, size: l

#1944 test: introduce slight delay to file acl test
  system-test/storage.ts
Labels: api: storage, size: s

#1876 fix!: drop node 10 support, update TypeScript, remove deprecated fields, remove configstore, align resumable upload behavior, utilize internalized CRC32C utilities
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  internal-tooling/README.md
  internal-tooling/performPerformanceTest.ts
  internal-tooling/performanceTest.ts
  package.json
  samples/package.json
  src/bucket.ts
  src/channel.ts
  src/crc32c.ts
  src/file.ts
  src/hash-stream-validator.ts
  src/index.ts
  src/nodejs-common/util.ts
  src/resumable-upload.ts
  src/signer.ts
  src/storage.ts
  system-test/kitchen.ts
  system-test/storage.ts
  test/bucket.ts
  test/crc32c.ts
  test/file.ts
  test/index.ts
  test/nodejs-common/util.ts
  test/resumable-upload.ts
  test/signer.ts
  tsconfig.json
Labels: api: storage, size: xl

#1965 chore: remove used dependencies
  package.json
Labels: api: storage, size: xs

#1969 fix: capture and throw on non-existent files
  src/bucket.ts
  test/bucket.ts
Labels: api: storage, size: s
