Repository googleapis/nodejs-storage, pull requests merged in 2022-04, with the labels that each got.

#1840 docs: add offset to createResumableUpload docs
  src/file.ts
Labels: api: storage

#1830 docs: add callout for crc32c checksum and md5 hash options
  src/file.ts
Labels: api: storage

#1839 chore(deps): Internalize common
  conformance-test/conformanceCommon.ts
  conformance-test/libraryMethods.ts
  package.json
  src/acl.ts
  src/bucket.ts
  src/channel.ts
  src/file.ts
  src/hmacKey.ts
  src/iam.ts
  src/nodejs-common/index.ts
  src/nodejs-common/operation.ts
  src/nodejs-common/service-object.ts
  src/nodejs-common/service.ts
  src/nodejs-common/util.ts
  src/notification.ts
  src/storage.ts
  system-test/common.ts
  system-test/storage.ts
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/hmacKey.ts
  test/iam.ts
  test/index.ts
  test/nodejs-common/index.ts
  test/nodejs-common/operation.ts
  test/nodejs-common/service-object.ts
  test/nodejs-common/service.ts
  test/nodejs-common/util.ts
  test/notification.ts
  tsconfig.json
Labels: api: storage

#1848 test: utilize unique filename in system tests
  system-test/storage.ts
Labels: api: storage, size: xs

#1857 fix: prevent retrying 200 response
  src/gcs-resumable-upload.ts
Labels: api: storage, size: xs

#1858 docs: mark function as private
  src/file.ts
Labels: api: storage, size: xs

#1860 chore!: removed deprecated fields
  src/bucket.ts
  src/file.ts
  src/nodejs-common/util.ts
  src/storage.ts
  system-test/storage.ts
  test/bucket.ts
  test/file.ts
  test/index.ts
  test/nodejs-common/util.ts
Labels: api: storage, size: l

#1862 chore(deps): update node-fetch to ^2.6.7
  package.json
  samples/package.json
Labels: api: storage, size: xs

#1864 fix!: default to resumable with no threshold
  src/bucket.ts
  test/bucket.ts
Labels: api: storage, size: m

#1872 fix: deleting, getting, and getting metadata for notifications
  conformance-test/test-data/retryInvocationMap.json
  src/nodejs-common/service-object.ts
  test/nodejs-common/service-object.ts
Labels: api: storage, size: s

#1871 fix!: remove configstore
  package.json
  src/file.ts
  src/gcs-resumable-upload.ts
  system-test/kitchen.ts
  system-test/storage.ts
  test/file.ts
  test/gcs-resumable-upload.ts
Labels: api: storage, size: l

#1877 build: remove 16
  .github/sync-repo-settings.yaml
Labels: api: storage, size: xs

#1880 fix: export idempotencystrategy and preconditionoptions from index
  src/index.ts
Labels: api: storage, size: xs

#1879 refactor: remove unnecessary types
  src/file.ts
  src/index.ts
Labels: api: storage, size: s

#1885 chore: do not let owlbot change repo settings
  owlbot.py
Labels: api: storage, size: xs

#1896 test: do not use a resumable upload for ACL file test
  system-test/storage.ts
Labels: api: storage, size: xs

#1895 fix: don't modify passed in options
  src/file.ts
  test/file.ts
Labels: api: storage, size: s

#1892 Build: Native TypeScript Support in Mocha
  conformance-test/libraryMethods.ts
  conformance-test/v4SignedUrl.ts
  package.json
  src/storage.ts
  system-test/storage.ts
  test/acl.ts
  test/bucket.ts
  test/channel.ts
  test/file.ts
  test/gcs-resumable-upload.ts
  test/iam.ts
  test/index.ts
  test/notification.ts
Labels: api: storage, size: m
