Repository googleapis/nodejs-storage, pull requests merged in 2022-12, with the labels that each got.

#2067 feat: implement parallel operations
  internal-tooling/performApplicationPerformanceTest.ts
  internal-tooling/performPerformanceTest.ts
  internal-tooling/performTransferManagerTest.ts
  internal-tooling/performanceTest.ts
  internal-tooling/performanceUtils.ts
  samples/downloadFileInChunksWithTransferManager.js
  samples/downloadManyFilesWithTransferManager.js
  samples/downloaded.txt
  samples/resources/test2.txt
  samples/system-test/transfer-manager.test.js
  samples/uploadManyFilesWithTransferManager.js
  src/index.ts
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: xl

#2110 feat: add crc32c validation option to chunked download, cleanup naming
  internal-tooling/performTransferManagerTest.ts
  internal-tooling/performanceTest.ts
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: m

#2109 feat: implement parallel operations (#2067)
  README.md
  internal-tooling/performApplicationPerformanceTest.ts
  internal-tooling/performPerformanceTest.ts
  internal-tooling/performTransferManagerTest.ts
  internal-tooling/performanceTest.ts
  internal-tooling/performanceUtils.ts
  samples/README.md
  samples/downloadFileInChunksWithTransferManager.js
  samples/downloadManyFilesWithTransferManager.js
  samples/downloaded.txt
  samples/resources/test2.txt
  samples/system-test/transfer-manager.test.js
  samples/uploadManyFilesWithTransferManager.js
  src/index.ts
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: xl

#2124 docs: update the docblock with more examples of loading credentials
  src/storage.ts
Labels: api: storage, size: s
