Repository googleapis/nodejs-storage, pull requests merged in 2023-10, with the labels that each got.

#2304 fix: make sure destination uses posix separator instead of win
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: s

#2323 fix: simplify the code for downloadInChunks
  src/transfer-manager.ts
Labels: api: storage, size: m

#2334 fix: add user-agent header to transfer manager and resumable upload
  src/nodejs-common/service.ts
  src/nodejs-common/util.ts
  src/resumable-upload.ts
  src/transfer-manager.ts
  src/util.ts
  test/nodejs-common/service.ts
  test/nodejs-common/util.ts
  test/resumable-upload.ts
  test/transfer-manager.ts
Labels: api: storage, size: m

#2336 fix: destroy sockets to stop memory leaking when stream errors
  src/file.ts
Labels: api: storage

#2338 fix: Close Open Handle for Empty Objects
  src/file.ts
Labels: api: storage, size: s

#2325 feat: support autoclass v2.1
  samples/getAutoclass.js
  samples/setAutoclass.js
  samples/system-test/buckets.test.js
  samples/system-test/files.test.js
  src/bucket.ts
  src/storage.ts
  system-test/storage.ts
Labels: api: storage, size: s
