Repository googleapis/nodejs-storage, pull requests merged in 2023-11, with the labels that each got.

#2333 feat: Resume Resumable Uploads
  src/file.ts
  src/hash-stream-validator.ts
  src/resumable-upload.ts
  system-test/kitchen.ts
  test/resumable-upload.ts
Labels: api: storage, size: l

#2358 test: fix dirname pathing for internal tools
  internal-tooling/performanceTest.ts
Labels: api: storage, size: xs

#2373 fix: TransferManager#downloadFileInChunks issues
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: m

#2365 feat: implement object retention lock for bucket / files
  src/bucket.ts
  src/file.ts
  src/storage.ts
  system-test/storage.ts
  test/file.ts
  test/index.ts
Labels: api: storage, size: m

#2378 test: fix incorrect time.getSeconds
  system-test/storage.ts
Labels: api: storage, size: xs
