Repository googleapis/nodejs-storage, pull requests merged in 2023-09, with the labels that each got.

#2287 chore: update transfer manager sample region tags
  samples/downloadFileInChunksWithTransferManager.js
  samples/downloadFolderWithTransferManager.js
  samples/downloadManyFilesWithTransferManager.js
  samples/uploadDirectoryWithTransferManager.js
  samples/uploadManyFilesWithTransferManager.js
Labels: api: storage, samples, size: s

#2293 fix: `File#save` iterable fixes
  src/file.ts
  test/file.ts
Labels: api: storage, size: m

#2291 feat: export `ApiError`
  src/index.ts
Labels: api: storage, size: xs

#2290 refactor: Dedupe `CreateResumableUpload`
  src/file.ts
Labels: api: storage, size: s

#2303 feat: add headers option to MPU
  src/transfer-manager.ts
  test/transfer-manager.ts
Labels: api: storage, size: l

#2305 feat: Transfer Manager Metrics
  src/file.ts
  src/nodejs-common/service.ts
  src/nodejs-common/util.ts
  src/resumable-upload.ts
  src/transfer-manager.ts
  test/file.ts
  test/nodejs-common/service.ts
  test/nodejs-common/util.ts
  test/resumable-upload.ts
  test/transfer-manager.ts
Labels: api: storage, size: l

#2315 build: Support Source Maps for Debugging
  package.json
Labels: api: storage, size: xs

#2316 test: cleanup delete logic in TM perf test
  internal-tooling/performTransferManagerTest.ts
Labels: api: storage, size: s
