Repository googleapis/nodejs-storage, pull requests merged in 2024-04, with the labels that each got.

#2428 samples: add samples for object retention
  README.md
  samples/README.md
  samples/createBucketWithObjectRetention.js
  samples/downloaded.txt
  samples/setObjectRetentionPolicy.js
  samples/system-test/buckets.test.js
  samples/system-test/files.test.js
Labels: api: storage, samples, size: m

#2431 feat: allow setting contentEncoding during compose
  src/bucket.ts
  src/nodejs-common/service.ts
  src/resumable-upload.ts
  src/transfer-manager.ts
  test/bucket.ts
Labels: api: storage, size: s

#2435 fix: remove extraneous mime-types package in favor of mime
  package.json
  src/bucket.ts
  src/file.ts
  test/bucket.ts
Labels: api: storage, size: s

#2442 fix: expand types of custom metadata within FileMetadata
  src/file.ts
Labels: size: xs

#2439 fix: change copyoptions type
  src/file.ts
  test/file.ts
Labels: api: storage, size: xs

#2449 fix: use correct indices for file.from and fix tests to verify names
  src/file.ts
  test/file.ts
Labels: size: s
